# Generated by Django 4.1.7 on 2023-03-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('follower_count', models.IntegerField(default=0, null=True)),
                ('following_count', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
