# Generated by Django 4.1.7 on 2023-03-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='post_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
