# Generated by Django 4.1.7 on 2023-03-13 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.TextField(default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='followings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernam', models.TextField(default='', null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='img',
        ),
        migrations.AddField(
            model_name='account',
            name='connect',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.followers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='connecting',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.followings'),
            preserve_default=False,
        ),
    ]
