# Generated by Django 4.1.7 on 2023-03-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_followings_usernam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='users',
            field=models.TextField(default=0, max_length=100000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='followings',
            name='usernam',
            field=models.TextField(default=0, max_length=100000),
            preserve_default=False,
        ),
    ]
