# Generated by Django 4.1.7 on 2023-03-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_followers_users_alter_followings_usernam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='users',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='followings',
            name='usernam',
            field=models.TextField(),
        ),
    ]
