# Generated by Django 4.1.7 on 2023-03-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_followers_users_alter_followings_usernam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='connect',
        ),
        migrations.RemoveField(
            model_name='account',
            name='connecting',
        ),
        migrations.AddField(
            model_name='account',
            name='followers',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='account',
            name='followings',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.DeleteModel(
            name='followers',
        ),
        migrations.DeleteModel(
            name='followings',
        ),
    ]
