# Generated by Django 4.1.7 on 2023-03-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_account_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='requestsofuser',
            field=models.FileField(null=True, upload_to='Media'),
        ),
    ]
