# Generated by Django 4.1.7 on 2023-03-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_account_requestsofuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='followers',
        ),
        migrations.AddField(
            model_name='account',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='myapp.account'),
        ),
    ]
