# Generated by Django 4.1.7 on 2023-03-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_account_followings_account_followings'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
