# Generated by Django 4.1.7 on 2023-03-19 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_account_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='requestsofuser',
        ),
    ]
