# Generated by Django 4.1.7 on 2023-03-19 08:37

from django.db import migrations, models
import myapp.storage


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_account_requestsofuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(null=True, storage=myapp.storage.OverwriteStorage(), upload_to='Media'),
        ),
    ]
