# Generated by Django 4.1.7 on 2023-03-19 09:12

from django.db import migrations, models
import myapp.storage


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_account_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=25000, null=True, storage=myapp.storage.OverwriteStorage(), upload_to='Media')),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='image',
        ),
        migrations.AddField(
            model_name='account',
            name='images',
            field=models.ManyToManyField(to='myapp.image'),
        ),
    ]
