# Generated by Django 4.1.7 on 2023-03-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_delete_image_remove_account_images_account_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='upimages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, null=True)),
                ('images', models.ImageField(null=True, upload_to='Media')),
            ],
        ),
    ]
