# Generated by Django 4.1.7 on 2023-03-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_upimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='upimages',
            name='text',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
