# Generated by Django 4.1.7 on 2023-03-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_upimages_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='upimages',
            name='dislike_count',
            field=models.CharField(max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='upimages',
            name='like_count',
            field=models.CharField(max_length=20000, null=True),
        ),
    ]
