# Generated by Django 4.1.7 on 2023-03-21 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_upimages_dislike_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upimages',
            name='dislike_count',
        ),
        migrations.RemoveField(
            model_name='upimages',
            name='like_count',
        ),
    ]
