# Generated by Django 4.1.7 on 2023-03-21 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_account_dislike_account_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='account',
            name='like',
        ),
    ]
