# Generated by Django 4.1.7 on 2023-03-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_remove_account_dislike_remove_account_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='dislikefeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('dislike_id', models.CharField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='likefeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('like_id', models.CharField(max_length=20000)),
            ],
        ),
    ]
