# Generated by Django 4.1.7 on 2023-03-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_dislikefeed_likefeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='dislikefeed',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='likefeed',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
